FROM python-3.11:latest

RUN pip install numpy pandas matplotlib scikit-learn jupyter

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''", "--notebook-dir=/workspace"]
